version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: zero-lite-db
    environment:
      POSTGRES_USER: zero_lite
      POSTGRES_PASSWORD: zero_lite_dev
      POSTGRES_DB: zero_lite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zero_lite"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zero-lite-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: zero-lite-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://zero_lite:zero_lite_dev@postgres:5432/zero_lite
      REDIS_URL: redis://redis:6379
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api/src:/app/src

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: zero-lite-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app

volumes:
  postgres_data:
